FROM golang:1.23-alpine

# Cài các công cụ cần thiết
RUN apk update && apk add --no-cache git curl

# Cài air để hot reload
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

# Tạo thư mục làm việc
WORKDIR /app

# Copy file cấu hình air trước để tận dụng cache
COPY ./be-event/.air.toml .

# Copy go.mod và go.sum để tải deps sớm
COPY ./be-event/go.mod ./be-event/go.sum ./
RUN go mod download

# Copy toàn bộ mã nguồn
COPY ./be-event .

# Copy file môi trường
COPY ./be-event/.env .env

# Mở cổng 8080
EXPOSE 8080

# Dùng air để chạy ứng dụng với hot reload
CMD ["air"]
